# Generated by Django 5.2.6 on 2025-09-22 05:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoardings', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hoardings.customer')),
                ('hoarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hoardings.hoarding')),
            ],
        ),
    ]
